import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image, ImageChops, ImageEnhance
import os

# --- 1. SAFE MEDIAPIPE INITIALIZATION ---
HAS_MEDIAPIPE = False
try:
    import mediapipe as mp
    from mediapipe.python.solutions import face_detection as mp_face_detection
    face_detector = mp_face_detection.FaceDetection(model_selection=1, min_detection_confidence=0.5)
    HAS_MEDIAPIPE = True
except Exception:
    HAS_MEDIAPIPE = False

# --- 2. PAGE CONFIG ---
st.set_page_config(page_title="Deepfake Defender Pro", layout="wide", page_icon="🛡️")

# --- 3. THE FORENSICS ENGINE (ELA) ---
def run_ela(image, quality=90):
    temp_file = "temp_ela_session.jpg"
    image.save(temp_file, 'JPEG', quality=quality)
    resaved = Image.open(temp_file)
    ela_map = ImageChops.difference(image, resaved)
    extrema = ela_map.getextrema()
    max_diff = max([ex[1] for ex in extrema])
    scale = 255.0 / max_diff if max_diff != 0 else 1
    ela_map = ImageEnhance.Brightness(ela_map).enhance(scale)
    return ela_map

# --- 4. MODEL LOADING ---
@st.cache_resource
def load_ensemble():
    # Ensure these filenames match your desktop folder exactly
    m1 = tf.keras.models.load_model('deepfake_detector_model.h5')
    m2 = tf.keras.models.load_model('pro_mobilenet_model.h5')
    return m1, m2

# --- 5. SIDEBAR ---
st.sidebar.title("🛡️ System Control")
st.sidebar.info("Deepfake Detection Site")
st.sidebar.write("**Status:** Dual-Ensemble Active")

# --- 6. MAIN APP ---
# --- STEP 6: MAIN INTERFACE ---
tab1, tab2= st.tabs(["🔍 AI Face Scan", "🧪 Image Forensics"])

uploaded_file = st.file_uploader("Upload Image...", type=["jpg", "jpeg", "png"])

if uploaded_file:
    img_orig = Image.open(uploaded_file).convert('RGB')
    img_array = np.array(img_orig)
    m1, m2 = load_ensemble()
    
    with tab1:
        st.header("Facial Analysis")
        
        # Safe Face Detection
        results = None
        if HAS_MEDIAPIPE:
            try: results = face_detector.process(img_array)
            except: results = None

        if results and results.detections:
            det = results.detections[0]
            bbox = det.location_data.relative_bounding_box
            h, w, _ = img_array.shape
            x, y, fw, fh = int(bbox.xmin * w), int(bbox.ymin * h), int(bbox.width * w), int(bbox.height * h)
            face_crop = img_array[max(0, y):y+fh, max(0, x):x+fw]
        else:
            face_crop = img_array

        # Prediction Logic
        processed = cv2.resize(face_crop, (224, 224)) / 255.0
        processed = np.expand_dims(processed, axis=0)
        
        score1 = m1.predict(processed)[0][0]
        score2 = m2.predict(processed)[0][0]
        ensemble_real_score = (score1 + score2) / 2

        # Display Results
        col1, col2 = st.columns(2)
        with col1:
            st.image(face_crop, caption="Analysis Target", use_container_width=True)
        
        with col2:
            if ensemble_real_score > 0.5:
                st.success(f"### RESULT: REAL\nConfidence: {ensemble_real_score*100:.2f}%")
                st.write(f"**Handmade Model:** {score1*100:.1f}% Real")
                st.write(f"**Pro Model:** {score2*100:.1f}% Real")
            else:
                # Calculate Fakeness for the display
                fakeness = (1 - ensemble_real_score) * 100
                st.error(f"### RESULT: FAKE\nThreat Level: {fakeness:.2f}% Fake")
                st.write(f"**Handmade Model:** {(1-score1)*100:.1f}% Fake")
                st.write(f"**Pro Model:** {(1-score2)*100:.1f}% Fake")

    with tab2:
        st.header("🧪 Background Integrity (ELA)")
        
        # --- ELA DESCRIPTION FOR USERS ---
        st.markdown("""
        **What are you seeing?**
        This is an **Error Level Analysis (ELA)** map. It detects digital tampering by identifying 
        different compression levels within a single image.
        
        * 🌑 **Dark/Uniform Areas:** High integrity. The pixels share the same digital history.
        * 💡 **Bright/Glowing Outlines:** Potential manipulation. If a face or object "glows" 
          significantly brighter than the rest of the image, it was likely modified or 
          generated by a separate AI process.
        """)
        
        st.divider()
        ela_img = run_ela(img_orig)
        st.image(ela_img, caption="Forensic Compression Map", use_container_width=True)